# Generated by Django 3.2.2 on 2021-12-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_client_id_user'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.client')),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='type_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='v_reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(max_length=50)),
                ('due_Date', models.DateField()),
                ('num_renovations', models.IntegerField()),
                ('id_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_type_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserve.type_doc'),
        ),
        migrations.CreateModel(
            name='p_reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_date', models.DateField()),
                ('id_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.reservation')),
            ],
        ),
    ]
