# Generated by Django 3.2.2 on 2021-12-06 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_audit_documents'),
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='licences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(max_length=50)),
                ('available', models.IntegerField()),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='v_reserve',
            name='id_licence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reserve.licences'),
            preserve_default=False,
        ),
    ]
