# Generated by Django 3.2.2 on 2021-12-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_audit_documents'),
        ('reserve', '0002_auto_20211205_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licences',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='v_reserve',
            name='id_licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.licences'),
        ),
    ]
