# Generated by Django 3.2.2 on 2021-12-06 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_id_user'),
        ('documents', '0002_audit_documents'),
        ('reserve', '0003_auto_20211205_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
