# Generated by Django 3.2.2 on 2021-11-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_posts', models.PositiveSmallIntegerField(default=0)),
                ('num_wait_posts', models.PositiveSmallIntegerField()),
                ('id_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.author_request')),
            ],
        ),
    ]
